export const Actions = {
    ADD_POST: 'ADD_POST',
    ADD_MESSAGE: 'ADD_MESSAGE',
    FOLLOW: 'FOLLOW',
    UNFOLLOW: 'UNFOLLOW',
    SET_USERS: 'SET_USERS',
    ADD_LIKE: 'ADD_LIKE',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_TOTAL_USERS_COUNT: 'SET_TOTAL_USERS_COUNT',
    IS_FETCHING: 'IS_FETCHING',
    SET_IS_FETCHING: 'SET_IS_FETCHING',
    SET_USER_PROFILE: 'SET_USER_PROFILE',

}
